/* Generated by scripts/generate.mjs. Do not edit. */

/**
 * Oxbit version 1 local theme pack. Appearance only; arbitrary CSS and remote assets are not supported.
 */
export interface ThemePack {
  $schema?: string;
  schemaVersion: 1;
  id: string;
  name: string;
  version: string;
  attribution?: string;
  /**
   * @maxItems 32
   */
  fonts?: {
    id: string;
    path: string;
    weight?: number;
    style?: "normal" | "italic" | "oblique";
  }[];
  /**
   * @minItems 1
   * @maxItems 128
   */
  themes: [
    {
      id: string;
      name: string;
      mode: "light" | "dark";
      highContrast?: boolean;
      pairedTheme?: string;
      /**
       * builtin:light, builtin:dark, or a local theme ID in this pack.
       */
      base?: string;
      colors?: {
        /**
         * workbench background
         */
        "workbench.background"?: string;
        /**
         * surface background
         */
        "surface.background"?: string;
        /**
         * editor background
         */
        "editor.background"?: string;
        /**
         * popover background
         */
        "popover.background"?: string;
        /**
         * input background
         */
        "input.background"?: string;
        /**
         * control hover background
         */
        "control.hover.background"?: string;
        /**
         * control active background
         */
        "control.active.background"?: string;
        /**
         * list selection background
         */
        "list.selection.background"?: string;
        /**
         * border default
         */
        "border.default"?: string;
        /**
         * border strong
         */
        "border.strong"?: string;
        /**
         * text primary
         */
        "text.primary"?: string;
        /**
         * text secondary
         */
        "text.secondary"?: string;
        /**
         * text muted
         */
        "text.muted"?: string;
        /**
         * text disabled
         */
        "text.disabled"?: string;
        /**
         * accent primary
         */
        "accent.primary"?: string;
        /**
         * accent foreground
         */
        "accent.foreground"?: string;
        /**
         * accent background
         */
        "accent.background"?: string;
        /**
         * focus border
         */
        "focus.border"?: string;
        /**
         * diagnostic error
         */
        "diagnostic.error"?: string;
        /**
         * diagnostic warning
         */
        "diagnostic.warning"?: string;
        /**
         * diagnostic info
         */
        "diagnostic.info"?: string;
        /**
         * diagnostic success
         */
        "diagnostic.success"?: string;
        /**
         * git modified
         */
        "git.modified"?: string;
        /**
         * git added
         */
        "git.added"?: string;
        /**
         * git deleted
         */
        "git.deleted"?: string;
        /**
         * git conflict
         */
        "git.conflict"?: string;
        /**
         * diagnostic error background
         */
        "diagnostic.error.background"?: string;
        /**
         * diagnostic warning background
         */
        "diagnostic.warning.background"?: string;
        /**
         * diff added background
         */
        "diff.added.background"?: string;
        /**
         * diff deleted background
         */
        "diff.deleted.background"?: string;
        /**
         * diagnostic info background
         */
        "diagnostic.info.background"?: string;
        /**
         * editor activeLine background
         */
        "editor.activeLine.background"?: string;
        /**
         * editor search background
         */
        "editor.search.background"?: string;
        /**
         * editor search activeBackground
         */
        "editor.search.activeBackground"?: string;
        /**
         * editor occurrence background
         */
        "editor.occurrence.background"?: string;
        /**
         * selection background
         */
        "selection.background"?: string;
        /**
         * editor guide
         */
        "editor.guide"?: string;
        /**
         * overlay background
         */
        "overlay.background"?: string;
        /**
         * button primary background
         */
        "button.primary.background"?: string;
        /**
         * button primary foreground
         */
        "button.primary.foreground"?: string;
        /**
         * button primary hoverBackground
         */
        "button.primary.hoverBackground"?: string;
        /**
         * link foreground
         */
        "link.foreground"?: string;
        /**
         * link hoverForeground
         */
        "link.hoverForeground"?: string;
        /**
         * selection foreground
         */
        "selection.foreground"?: string;
        /**
         * editor selection background
         */
        "editor.selection.background"?: string;
        /**
         * editor selection foreground
         */
        "editor.selection.foreground"?: string;
        /**
         * editor selection inactiveBackground
         */
        "editor.selection.inactiveBackground"?: string;
        /**
         * editor cursor
         */
        "editor.cursor"?: string;
        /**
         * editor gutter background
         */
        "editor.gutter.background"?: string;
        /**
         * editor gutter foreground
         */
        "editor.gutter.foreground"?: string;
        /**
         * popover foreground
         */
        "popover.foreground"?: string;
        /**
         * input foreground
         */
        "input.foreground"?: string;
        /**
         * input placeholder
         */
        "input.placeholder"?: string;
        /**
         * control disabled foreground
         */
        "control.disabled.foreground"?: string;
        /**
         * tab active foreground
         */
        "tab.active.foreground"?: string;
        /**
         * tab inactive foreground
         */
        "tab.inactive.foreground"?: string;
        /**
         * tab hover background
         */
        "tab.hover.background"?: string;
        /**
         * preview background
         */
        "preview.background"?: string;
        /**
         * preview foreground
         */
        "preview.foreground"?: string;
        /**
         * collaboration cursor
         */
        "collaboration.cursor"?: string;
        /**
         * collaboration selection
         */
        "collaboration.selection"?: string;
        /**
         * terminal background
         */
        "terminal.background"?: string;
        /**
         * terminal foreground
         */
        "terminal.foreground"?: string;
        /**
         * terminal cursor
         */
        "terminal.cursor"?: string;
        /**
         * terminal cursorAccent
         */
        "terminal.cursorAccent"?: string;
        /**
         * terminal selectionBackground
         */
        "terminal.selectionBackground"?: string;
        /**
         * terminal selectionForeground
         */
        "terminal.selectionForeground"?: string;
        /**
         * terminal selectionInactiveBackground
         */
        "terminal.selectionInactiveBackground"?: string;
        /**
         * terminal search background
         */
        "terminal.search.background"?: string;
        /**
         * terminal search activeBackground
         */
        "terminal.search.activeBackground"?: string;
        /**
         * terminal search border
         */
        "terminal.search.border"?: string;
        /**
         * Terminal ANSI black
         */
        "terminal.black"?: string;
        /**
         * Terminal ANSI red
         */
        "terminal.red"?: string;
        /**
         * Terminal ANSI green
         */
        "terminal.green"?: string;
        /**
         * Terminal ANSI yellow
         */
        "terminal.yellow"?: string;
        /**
         * Terminal ANSI blue
         */
        "terminal.blue"?: string;
        /**
         * Terminal ANSI magenta
         */
        "terminal.magenta"?: string;
        /**
         * Terminal ANSI cyan
         */
        "terminal.cyan"?: string;
        /**
         * Terminal ANSI white
         */
        "terminal.white"?: string;
        /**
         * Terminal ANSI brightBlack
         */
        "terminal.brightBlack"?: string;
        /**
         * Terminal ANSI brightRed
         */
        "terminal.brightRed"?: string;
        /**
         * Terminal ANSI brightGreen
         */
        "terminal.brightGreen"?: string;
        /**
         * Terminal ANSI brightYellow
         */
        "terminal.brightYellow"?: string;
        /**
         * Terminal ANSI brightBlue
         */
        "terminal.brightBlue"?: string;
        /**
         * Terminal ANSI brightMagenta
         */
        "terminal.brightMagenta"?: string;
        /**
         * Terminal ANSI brightCyan
         */
        "terminal.brightCyan"?: string;
        /**
         * Terminal ANSI brightWhite
         */
        "terminal.brightWhite"?: string;
        /**
         * File badge default foreground
         */
        "fileBadge.default.foreground"?: string;
        /**
         * File badge default background
         */
        "fileBadge.default.background"?: string;
        /**
         * File badge typescript foreground
         */
        "fileBadge.typescript.foreground"?: string;
        /**
         * File badge typescript background
         */
        "fileBadge.typescript.background"?: string;
        /**
         * File badge javascript foreground
         */
        "fileBadge.javascript.foreground"?: string;
        /**
         * File badge javascript background
         */
        "fileBadge.javascript.background"?: string;
        /**
         * File badge css foreground
         */
        "fileBadge.css.foreground"?: string;
        /**
         * File badge css background
         */
        "fileBadge.css.background"?: string;
        /**
         * File badge html foreground
         */
        "fileBadge.html.foreground"?: string;
        /**
         * File badge html background
         */
        "fileBadge.html.background"?: string;
      };
      syntax?: {
        /**
         * Parser category keyword
         */
        keyword?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category string
         */
        string?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category number
         */
        number?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category comment
         */
        comment?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category type
         */
        type?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category function
         */
        function?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category property
         */
        property?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category variable
         */
        variable?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category ident
         */
        ident?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category text
         */
        text?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category tag
         */
        tag?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category attr
         */
        attr?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category punct
         */
        punct?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category operator
         */
        operator?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category heading
         */
        heading?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category link
         */
        link?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category strong
         */
        strong?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Markdown emphasis
         */
        emphasis?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
      };
      typography?: {
        /**
         * Typography for body
         */
        body?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
        /**
         * Typography for heading
         */
        heading?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
        /**
         * Typography for label
         */
        label?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
        /**
         * Typography for small
         */
        small?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
        /**
         * Typography for mono
         */
        mono?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
        /**
         * Typography for editor
         */
        editor?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
        /**
         * Typography for terminal
         */
        terminal?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
        /**
         * Typography for document
         */
        document?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
      };
      effects?: {
        /**
         * Structured shadows; an empty array disables elevation.
         *
         * @maxItems 8
         */
        shadow?:
          | []
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ]
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ]
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ]
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ]
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ]
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ]
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ]
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ];
      };
    },
    ...{
      id: string;
      name: string;
      mode: "light" | "dark";
      highContrast?: boolean;
      pairedTheme?: string;
      /**
       * builtin:light, builtin:dark, or a local theme ID in this pack.
       */
      base?: string;
      colors?: {
        /**
         * workbench background
         */
        "workbench.background"?: string;
        /**
         * surface background
         */
        "surface.background"?: string;
        /**
         * editor background
         */
        "editor.background"?: string;
        /**
         * popover background
         */
        "popover.background"?: string;
        /**
         * input background
         */
        "input.background"?: string;
        /**
         * control hover background
         */
        "control.hover.background"?: string;
        /**
         * control active background
         */
        "control.active.background"?: string;
        /**
         * list selection background
         */
        "list.selection.background"?: string;
        /**
         * border default
         */
        "border.default"?: string;
        /**
         * border strong
         */
        "border.strong"?: string;
        /**
         * text primary
         */
        "text.primary"?: string;
        /**
         * text secondary
         */
        "text.secondary"?: string;
        /**
         * text muted
         */
        "text.muted"?: string;
        /**
         * text disabled
         */
        "text.disabled"?: string;
        /**
         * accent primary
         */
        "accent.primary"?: string;
        /**
         * accent foreground
         */
        "accent.foreground"?: string;
        /**
         * accent background
         */
        "accent.background"?: string;
        /**
         * focus border
         */
        "focus.border"?: string;
        /**
         * diagnostic error
         */
        "diagnostic.error"?: string;
        /**
         * diagnostic warning
         */
        "diagnostic.warning"?: string;
        /**
         * diagnostic info
         */
        "diagnostic.info"?: string;
        /**
         * diagnostic success
         */
        "diagnostic.success"?: string;
        /**
         * git modified
         */
        "git.modified"?: string;
        /**
         * git added
         */
        "git.added"?: string;
        /**
         * git deleted
         */
        "git.deleted"?: string;
        /**
         * git conflict
         */
        "git.conflict"?: string;
        /**
         * diagnostic error background
         */
        "diagnostic.error.background"?: string;
        /**
         * diagnostic warning background
         */
        "diagnostic.warning.background"?: string;
        /**
         * diff added background
         */
        "diff.added.background"?: string;
        /**
         * diff deleted background
         */
        "diff.deleted.background"?: string;
        /**
         * diagnostic info background
         */
        "diagnostic.info.background"?: string;
        /**
         * editor activeLine background
         */
        "editor.activeLine.background"?: string;
        /**
         * editor search background
         */
        "editor.search.background"?: string;
        /**
         * editor search activeBackground
         */
        "editor.search.activeBackground"?: string;
        /**
         * editor occurrence background
         */
        "editor.occurrence.background"?: string;
        /**
         * selection background
         */
        "selection.background"?: string;
        /**
         * editor guide
         */
        "editor.guide"?: string;
        /**
         * overlay background
         */
        "overlay.background"?: string;
        /**
         * button primary background
         */
        "button.primary.background"?: string;
        /**
         * button primary foreground
         */
        "button.primary.foreground"?: string;
        /**
         * button primary hoverBackground
         */
        "button.primary.hoverBackground"?: string;
        /**
         * link foreground
         */
        "link.foreground"?: string;
        /**
         * link hoverForeground
         */
        "link.hoverForeground"?: string;
        /**
         * selection foreground
         */
        "selection.foreground"?: string;
        /**
         * editor selection background
         */
        "editor.selection.background"?: string;
        /**
         * editor selection foreground
         */
        "editor.selection.foreground"?: string;
        /**
         * editor selection inactiveBackground
         */
        "editor.selection.inactiveBackground"?: string;
        /**
         * editor cursor
         */
        "editor.cursor"?: string;
        /**
         * editor gutter background
         */
        "editor.gutter.background"?: string;
        /**
         * editor gutter foreground
         */
        "editor.gutter.foreground"?: string;
        /**
         * popover foreground
         */
        "popover.foreground"?: string;
        /**
         * input foreground
         */
        "input.foreground"?: string;
        /**
         * input placeholder
         */
        "input.placeholder"?: string;
        /**
         * control disabled foreground
         */
        "control.disabled.foreground"?: string;
        /**
         * tab active foreground
         */
        "tab.active.foreground"?: string;
        /**
         * tab inactive foreground
         */
        "tab.inactive.foreground"?: string;
        /**
         * tab hover background
         */
        "tab.hover.background"?: string;
        /**
         * preview background
         */
        "preview.background"?: string;
        /**
         * preview foreground
         */
        "preview.foreground"?: string;
        /**
         * collaboration cursor
         */
        "collaboration.cursor"?: string;
        /**
         * collaboration selection
         */
        "collaboration.selection"?: string;
        /**
         * terminal background
         */
        "terminal.background"?: string;
        /**
         * terminal foreground
         */
        "terminal.foreground"?: string;
        /**
         * terminal cursor
         */
        "terminal.cursor"?: string;
        /**
         * terminal cursorAccent
         */
        "terminal.cursorAccent"?: string;
        /**
         * terminal selectionBackground
         */
        "terminal.selectionBackground"?: string;
        /**
         * terminal selectionForeground
         */
        "terminal.selectionForeground"?: string;
        /**
         * terminal selectionInactiveBackground
         */
        "terminal.selectionInactiveBackground"?: string;
        /**
         * terminal search background
         */
        "terminal.search.background"?: string;
        /**
         * terminal search activeBackground
         */
        "terminal.search.activeBackground"?: string;
        /**
         * terminal search border
         */
        "terminal.search.border"?: string;
        /**
         * Terminal ANSI black
         */
        "terminal.black"?: string;
        /**
         * Terminal ANSI red
         */
        "terminal.red"?: string;
        /**
         * Terminal ANSI green
         */
        "terminal.green"?: string;
        /**
         * Terminal ANSI yellow
         */
        "terminal.yellow"?: string;
        /**
         * Terminal ANSI blue
         */
        "terminal.blue"?: string;
        /**
         * Terminal ANSI magenta
         */
        "terminal.magenta"?: string;
        /**
         * Terminal ANSI cyan
         */
        "terminal.cyan"?: string;
        /**
         * Terminal ANSI white
         */
        "terminal.white"?: string;
        /**
         * Terminal ANSI brightBlack
         */
        "terminal.brightBlack"?: string;
        /**
         * Terminal ANSI brightRed
         */
        "terminal.brightRed"?: string;
        /**
         * Terminal ANSI brightGreen
         */
        "terminal.brightGreen"?: string;
        /**
         * Terminal ANSI brightYellow
         */
        "terminal.brightYellow"?: string;
        /**
         * Terminal ANSI brightBlue
         */
        "terminal.brightBlue"?: string;
        /**
         * Terminal ANSI brightMagenta
         */
        "terminal.brightMagenta"?: string;
        /**
         * Terminal ANSI brightCyan
         */
        "terminal.brightCyan"?: string;
        /**
         * Terminal ANSI brightWhite
         */
        "terminal.brightWhite"?: string;
        /**
         * File badge default foreground
         */
        "fileBadge.default.foreground"?: string;
        /**
         * File badge default background
         */
        "fileBadge.default.background"?: string;
        /**
         * File badge typescript foreground
         */
        "fileBadge.typescript.foreground"?: string;
        /**
         * File badge typescript background
         */
        "fileBadge.typescript.background"?: string;
        /**
         * File badge javascript foreground
         */
        "fileBadge.javascript.foreground"?: string;
        /**
         * File badge javascript background
         */
        "fileBadge.javascript.background"?: string;
        /**
         * File badge css foreground
         */
        "fileBadge.css.foreground"?: string;
        /**
         * File badge css background
         */
        "fileBadge.css.background"?: string;
        /**
         * File badge html foreground
         */
        "fileBadge.html.foreground"?: string;
        /**
         * File badge html background
         */
        "fileBadge.html.background"?: string;
      };
      syntax?: {
        /**
         * Parser category keyword
         */
        keyword?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category string
         */
        string?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category number
         */
        number?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category comment
         */
        comment?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category type
         */
        type?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category function
         */
        function?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category property
         */
        property?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category variable
         */
        variable?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category ident
         */
        ident?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category text
         */
        text?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category tag
         */
        tag?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category attr
         */
        attr?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category punct
         */
        punct?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category operator
         */
        operator?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category heading
         */
        heading?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category link
         */
        link?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Parser category strong
         */
        strong?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
        /**
         * Markdown emphasis
         */
        emphasis?: {
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          foreground?: string;
          /**
           * Hexadecimal sRGB color, optional alpha, or transparent.
           */
          background?: string;
          weight?: number;
          italic?: boolean;
          underline?: boolean;
        };
      };
      typography?: {
        /**
         * Typography for body
         */
        body?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
        /**
         * Typography for heading
         */
        heading?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
        /**
         * Typography for label
         */
        label?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
        /**
         * Typography for small
         */
        small?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
        /**
         * Typography for mono
         */
        mono?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
        /**
         * Typography for editor
         */
        editor?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
        /**
         * Typography for terminal
         */
        terminal?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
        /**
         * Typography for document
         */
        document?: {
          /**
           * Local font ID or installed family followed by fallback families. No CSS or URLs.
           *
           * @minItems 1
           * @maxItems 12
           */
          family?:
            | [string]
            | [string, string]
            | [string, string, string]
            | [string, string, string, string]
            | [string, string, string, string, string]
            | [string, string, string, string, string, string]
            | [string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string]
            | [string, string, string, string, string, string, string, string, string, string, string, string];
          size?: number;
          weight?: number;
          style?: "normal" | "italic" | "oblique";
          lineHeight?: number;
          letterSpacing?: number;
          ligatures?: boolean;
          axes?: {
            [k: string]: number;
          };
        };
      };
      effects?: {
        /**
         * Structured shadows; an empty array disables elevation.
         *
         * @maxItems 8
         */
        shadow?:
          | []
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ]
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ]
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ]
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ]
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ]
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ]
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ]
          | [
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              },
              {
                x: number;
                y: number;
                blur: number;
                spread: number;
                /**
                 * Hexadecimal sRGB color, optional alpha, or transparent.
                 */
                color: string;
              }
            ];
      };
    }[]
  ];
}
