import schema from "./settings.schema.json";

/** Generated by pnpm settings:schema from built-in configuration declarations. */
export const settingsSchema = schema;
export const SETTINGS_SCHEMA_URI = schema.$id;
