const extensions: Record<string, string[]> = {
  javascript: ["js", "mjs", "cjs", "jsx"],
  typescript: ["ts", "mts", "cts"],
  react: ["tsx"],
  json: ["json", "jsonc", "json5", "map"],
  html: ["html", "htm", "xhtml", "svelte"],
  css: ["css", "scss", "sass", "less", "styl"],
  markdown: ["md", "markdown", "mdx", "rst", "adoc"],
  python: ["py", "pyi", "pyw", "ipynb"],
  rust: ["rs"],
  go: ["go", "mod", "sum"],
  java: ["java", "class", "jar", "kt", "kts", "gradle"],
  clike: ["c", "h", "cc", "cpp", "cxx", "hpp", "hh", "m", "mm"],
  ruby: ["rb", "erb", "gemspec"],
  php: ["php", "phtml"],
  shell: ["sh", "bash", "zsh", "fish", "bat", "cmd", "ps1"],
  sql: ["sql", "psql", "prisma"],
  yaml: ["yml", "yaml"],
  toml: ["toml", "ini", "cfg", "conf", "env", "properties"],
  xml: ["xml", "xsd", "xsl", "plist", "csproj", "storyboard"],
  swift: ["swift"],
  csharp: ["cs", "csx", "fs", "vb"],
  vue: ["vue"],
  text: ["txt", "log", "text", "nfo", "rtf"],
  image: ["png", "jpg", "jpeg", "gif", "bmp", "ico", "webp", "svg", "avif"],
  media: ["mp3", "wav", "ogg", "flac", "mp4", "mov", "webm", "avi", "mkv"],
  archive: ["zip", "tar", "gz", "bz2", "xz", "7z", "rar", "vsix", "cab"],
  binary: ["exe", "dll", "com", "so", "dylib", "bin", "wasm", "o", "a"],
  font: ["ttf", "otf", "woff", "woff2", "eot", "fon"],
  database: ["db", "sqlite", "sqlite3", "mdb", "parquet"],
  lock: ["lock", "pem", "key", "crt", "p12", "keystore"],
  file: ["pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx"],
};

const names: Record<string, string[]> = {
  git: [
    ".gitignore",
    ".gitattributes",
    ".gitmodules",
    ".gitkeep",
    "commit_editmsg",
  ],
  json: ["package.json", "tsconfig.json", "composer.json"],
  lock: [
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "bun.lock",
    "bun.lockb",
    "cargo.lock",
    "poetry.lock",
    "gemfile.lock",
  ],
  text: ["license", "licence", "notice", "authors", "copying", "changelog"],
  markdown: ["readme", "readme.md", "contributing.md", "changelog.md"],
  toml: [
    ".editorconfig",
    ".npmrc",
    ".nvmrc",
    ".env",
    ".env.local",
    "makefile",
    "dockerfile",
    ".dockerignore",
  ],
  shell: [".bashrc", ".zshrc", ".profile", ".bash_profile"],
};

const languages: Record<string, string[]> = {
  javascript: ["javascript", "javascriptreact"],
  typescript: ["typescript"],
  react: ["typescriptreact"],
  json: ["json", "jsonc"],
  html: ["html", "handlebars"],
  css: ["css", "scss", "less"],
  markdown: ["markdown"],
  python: ["python"],
  rust: ["rust"],
  go: ["go"],
  java: ["java", "kotlin", "groovy"],
  clike: ["c", "cpp", "objective-c", "objective-cpp"],
  ruby: ["ruby"],
  php: ["php"],
  shell: ["shellscript", "bat", "powershell"],
  sql: ["sql"],
  yaml: ["yaml"],
  toml: ["toml", "ini", "properties", "dockerfile", "makefile"],
  xml: ["xml", "xsl"],
  swift: ["swift"],
  csharp: ["csharp", "fsharp", "vb"],
  vue: ["vue"],
  text: ["plaintext", "log"],
};

const invert = (source: Record<string, string[]>) =>
  Object.fromEntries(
    Object.entries(source).flatMap(([definition, keys]) =>
      keys.map((key) => [key, definition]),
    ),
  );

export const fileAssociations = {
  file: "file",
  folder: "folder",
  folderExpanded: "folderOpen",
  rootFolder: "drive",
  rootFolderExpanded: "driveOpen",
  fileExtensions: invert(extensions),
  fileNames: invert(names),
  languageIds: invert(languages),
};
