import { bitmap, page } from "./bitmap.js";

/** Two ruled lines above a two-tone chip, the way 98-era shell icons coded types. */
const coded = (light: string, dark: string) =>
  page([
    "ddddddd..",
    ".........",
    "ddddddddd",
    ".........",
    light.repeat(9),
    dark.repeat(9),
    ".........",
  ]);

const text = page([
  "ddddddd..",
  ".........",
  "ddddddddd",
  ".........",
  "ddddddddd",
  ".........",
  "dddddd...",
]);

export const fileShapes: Record<string, string[]> = {
  file: page([
    "ddddddd..",
    ".........",
    "ddddddddd",
    ".........",
    "ddddddddd",
    ".........",
    ".........",
  ]),
  text,
  markdown: page([
    "kk.....kk",
    "kkk...kkk",
    "kkkk.kkkk",
    "k.kkkkk.k",
    "k..kkk..k",
    "k...k...k",
    ".........",
  ]),
  image: page([
    "bbbbbbbbb",
    "bbyybbbbb",
    "bbyybbbbb",
    "bbbbbbGbb",
    "bbbbbGGGb",
    "bbbGGGGGG",
    "GGGGGGGGG",
  ]),
  media: page([
    ".........",
    "..k......",
    "..kkk....",
    "..kkkkk..",
    "..kkk....",
    "..k......",
    ".........",
  ]),
  archive: page([
    "...ww....",
    "...kk....",
    "...ww....",
    "...kk....",
    "...ww....",
    "..YkkY...",
    "..YYYY...",
  ]),
  binary: page([
    "ggggggggg",
    "BBBBBBBBB",
    "gggggggkg",
    "gkkkkkgkg",
    "gkkkkkgkg",
    "gkkkkkgkg",
    "ggggggggg",
  ]),
  font: page([
    "...kk....",
    "...kk....",
    "..k..k...",
    "..kkkkk..",
    ".kk...kk.",
    ".kk...kk.",
    ".........",
  ]),
  database: page([
    ".ddddddd.",
    ".dwwwwwd.",
    ".ddddddd.",
    ".dwwwwwd.",
    ".ddddddd.",
    ".dwwwwwd.",
    ".ddddddd.",
  ]),
  lock: page([
    "...ddd...",
    "..d...d..",
    "..d...d..",
    ".YYYYYYY.",
    ".YYYkYYY.",
    ".YYYkYYY.",
    ".YYYYYYY.",
  ]),
  folder: [
    "................",
    "................",
    ".kkkk...........",
    ".kYYkkkkkkkk....",
    ".kYYYYYYYYYYk...",
    ".kYyyyyyyyyyYk..",
    ".kYyyyyyyyyyyk..",
    ".kYyyyyyyyyyyk..",
    ".kYyyyyyyyyyyk..",
    ".kYyyyyyyyyyyk..",
    ".kYyyyyyyyyyyk..",
    ".kYyyyyyyyyyyk..",
    ".kYYYYYYYYYYYk..",
    ".kkkkkkkkkkkkk..",
    "................",
    "................",
  ],
  folderOpen: [
    "................",
    "................",
    ".kkkk...........",
    ".kYYkkkkkkkk....",
    ".kYYYYYYYYYYk...",
    ".kYyyyyyyyyyYk..",
    ".kYyyyyykkkkkkk.",
    ".kYyyykkyyyyyyk.",
    ".kYyykkyyyyyyk..",
    ".kYykkyyyyyyk...",
    ".kYkkyyyyyyk....",
    ".kkkyyyyyyk.....",
    "..kkkkkkkk......",
    "................",
    "................",
    "................",
  ],
  drive: [
    "................",
    "................",
    "..kkkkkkkkkkkk..",
    "..kssssssssssk..",
    "..kggggggggggk..",
    "..kggggggggggk..",
    "..kggggggggggk..",
    "..kggggggggggk..",
    "..kkkkkkkkkkkk..",
    "..kgggggggggdk..",
    "..kglkgggggddk..",
    "..kgggggggddgk..",
    "..kkkkkkkkkkkk..",
    "................",
    "................",
    "................",
  ],
  driveOpen: [
    "................",
    "................",
    "..kkkkkkkkkkkk..",
    "..kssssssssssk..",
    "..kggggggggggk..",
    "..kggggggggggk..",
    "..kggggggggggk..",
    "..kggggggggggk..",
    "..kkkkkkkkkkkk..",
    "..kgggggggggdk..",
    "..kgykgggggddk..",
    "..kgggggggddgk..",
    "..kkkkkkkkkkkk..",
    "................",
    "................",
    "................",
  ],
};

/** Chip colours follow the VGA palette rather than modern brand colours. */
const chips: Record<string, [string, string]> = {
  javascript: ["y", "Y"],
  typescript: ["c", "C"],
  json: ["l", "G"],
  html: ["r", "R"],
  css: ["m", "M"],
  python: ["b", "B"],
  rust: ["Y", "R"],
  go: ["c", "B"],
  java: ["R", "k"],
  clike: ["b", "B"],
  ruby: ["r", "R"],
  php: ["M", "B"],
  shell: ["d", "k"],
  sql: ["C", "B"],
  yaml: ["l", "C"],
  toml: ["Y", "R"],
  xml: ["G", "Y"],
  git: ["r", "R"],
  react: ["c", "B"],
  vue: ["G", "C"],
  swift: ["r", "Y"],
  csharp: ["M", "B"],
};

export const fileDefinitions: Record<string, string> = Object.fromEntries([
  ...Object.entries(fileShapes).map(([id, rows]) => [id, bitmap(rows)]),
  ...Object.entries(chips).map(([id, [light, dark]]) => [
    id,
    bitmap(coded(light, dark)),
  ]),
]);
