import {afterEach,describe,expect,it} from 'vitest';
import * as fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {pathToFileURL} from 'node:url';
import {Git} from '../src/git.js';
import {WorkspaceFiles} from '../src/filesystem.js';
import {runCommand} from '../src/processes.js';

describe('local Git remotes and recovery',()=>{
  const directories:string[]=[];
  afterEach(async()=>{for(const directory of directories.splice(0))await fs.rm(directory,{recursive:true,force:true});});
  const command=async(cwd:string,args:string[])=>{const result=await runCommand('git',args,{cwd});if(result.exitCode)throw new Error(result.stderr);return result.stdout.trim();};
  async function setup(){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'zapp-remote-'));directories.push(directory);const root=path.join(directory,'workspace'),remote=path.join(directory,'remote.git');await fs.mkdir(root);await command(directory,['init','--bare','--initial-branch=main',remote]);await command(root,['init','--initial-branch=main']);await command(root,['config','user.name','Zapp Test']);await command(root,['config','user.email','zapp@example.test']);await fs.writeFile(path.join(root,'file.txt'),'first\n');const git=new Git(new WorkspaceFiles(root)),signal=new AbortController().signal;await git.action('stage',{path:'file.txt'},signal,()=>{});await git.action('commit',{message:'test: seed remote'},signal,()=>{});await command(root,['remote','add','origin',pathToFileURL(remote).href]);await command(root,['push','--set-upstream','origin','main']);return {directory,root,remote,git,signal};}
  it('clones, pushes and fetches against a real local bare remote',async()=>{const {root,remote,git,signal}=await setup();const progress:string[]=[];expect(await git.action('clone',{url:pathToFileURL(remote).href,destination:'clones/project'},signal,value=>progress.push(value))).toEqual({path:'clones/project'});const clone=path.join(root,'clones/project');expect(await fs.readFile(path.join(clone,'file.txt'),'utf8')).toBe('first\n');await fs.writeFile(path.join(root,'file.txt'),'second\n');await git.action('stage',{path:'file.txt'},signal,()=>{});const commit=await git.action('commit',{message:'test: push change'},signal,()=>{});await git.action('push',{},signal,value=>progress.push(value));const clonedGit=new Git(new WorkspaceFiles(clone));await clonedGit.action('fetch',{},signal,value=>progress.push(value));expect(await command(clone,['rev-parse','origin/main'])).toBe((commit as {commit:string}).commit);expect(await command(clone,['show','origin/main:file.txt'])).toBe('second');expect(progress.join('')).toContain('Cloning');});
  it('preserves a successful clone when simultaneous destination reservation fails',async()=>{const {root,remote,git,signal}=await setup();const results=await Promise.allSettled([git.action('clone',{url:pathToFileURL(remote).href,destination:'same'},signal,()=>{}),git.action('clone',{url:pathToFileURL(remote).href,destination:'same'},signal,()=>{})]);expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);expect(await fs.readFile(path.join(root,'same/file.txt'),'utf8')).toBe('first\n');});
  it('cleans failed or cancelled clones and preserves disk changes on checkout refusal',async()=>{const {root,remote,git,signal}=await setup();await expect(git.action('clone',{url:pathToFileURL(remote+'-missing').href,destination:'failed'},signal,()=>{})).rejects.toMatchObject({code:'GIT_FAILED'});await expect(fs.stat(path.join(root,'failed'))).rejects.toMatchObject({code:'ENOENT'});const cancellation=new AbortController();cancellation.abort();await expect(git.action('clone',{url:pathToFileURL(remote).href,destination:'cancelled'},cancellation.signal,()=>{})).rejects.toMatchObject({code:'CANCELLED'});await expect(fs.stat(path.join(root,'cancelled'))).rejects.toMatchObject({code:'ENOENT'});await command(root,['checkout','-b','other']);await fs.writeFile(path.join(root,'file.txt'),'other branch\n');await git.action('stage',{path:'file.txt'},signal,()=>{});await git.action('commit',{message:'test: other branch'},signal,()=>{});await command(root,['checkout','main']);await fs.writeFile(path.join(root,'file.txt'),'unsaved on disk\n');await expect(git.action('checkout',{branch:'other'},signal,()=>{})).rejects.toMatchObject({code:'GIT_FAILED'});expect(await fs.readFile(path.join(root,'file.txt'),'utf8')).toBe('unsaved on disk\n');expect((await git.status()).branch).toBe('main');});
});
