import {afterEach,describe,expect,it,vi} from 'vitest';
import * as Y from 'yjs';
import {createKernel} from '../../../core/src/index.js';
import {DocumentService} from '../../../documents/src/index.js';
import {RuntimeFileSystem} from '../../../host-runtime/src/index.js';
import {CollaborationService} from './index.js';
import type {FeatureOptions,Persistence,RpcClient} from '@oxbit/sdk';

afterEach(()=>vi.unstubAllGlobals());
describe('shared document lifecycle',()=>{
  async function setup(){vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{}});const server=new Y.Doc();server.getText('content').insert(0,'saved');const calls:string[]=[],listeners=new Map<string,Set<(value:any)=>void>>();const runtime:RpcClient={connected:true,async request<T>(method:string,params:Record<string,unknown>={}){calls.push(method);if(method==='fs.read')return {path:params.path,text:'saved',revision:'r1',encoding:'utf-8',eol:'LF'} as T;if(method==='collab.join')return {update:Buffer.from(Y.encodeStateAsUpdate(server)).toString('base64'),revision:'r1',savedText:'saved'} as T;if(method==='collab.update')Y.applyUpdate(server,Buffer.from(params.update as string,'base64'));return {ok:true} as T;},subscribe(event,listener){const set=listeners.get(event)??new Set();set.add(listener);listeners.set(event,set);return()=>{set.delete(listener);};}};const values=new Map<string,unknown>(),persistence:Persistence={get:async<T>(key:string)=>values.get(key) as T|undefined,set:async(key,value)=>{values.set(key,value);},delete:async key=>{values.delete(key);}};const kernel=createKernel(),filesystem=new RuntimeFileSystem(runtime),documents=new DocumentService(filesystem,persistence,kernel),doc=await documents.open('file.ts');const options={kernel,documents,filesystem,runtime,workbench:{notify:()=>{},openFile:async()=>{}}} as unknown as FeatureOptions;return {server,calls,kernel,filesystem,documents,doc,options};}
  it('uploads recovered unsaved text and leaves closed rooms',async()=>{const fixture=await setup();fixture.doc.replace('recovered draft');const collaboration=new CollaborationService(fixture.options);await collaboration.flush();expect(fixture.server.getText('content').toString()).toBe('recovered draft');fixture.documents.discard('file.ts');expect(fixture.calls).toContain('collab.leave');expect(fixture.filesystem.shared.has('file.ts')).toBe(false);collaboration.dispose();await fixture.documents.dispose();fixture.kernel.dispose();fixture.server.destroy();});
  it('preserves local edits while the synchronization feature is disabled',async()=>{const fixture=await setup();const collaboration=new CollaborationService(fixture.options);collaboration.dispose();fixture.doc.replace('unsynchronized local text');await expect(fixture.documents.save('file.ts')).rejects.toThrow('Enable collaboration');expect(fixture.doc.text.toString()).toBe('unsynchronized local text');expect(fixture.server.getText('content').toString()).toBe('saved');await fixture.documents.dispose();fixture.kernel.dispose();fixture.server.destroy();});
});
