import type { Keymap } from "./types.js";
export const atom: Keymap = {
  stableId: "atom",
  title: "Atom",
  description:
    "Atom defaults: Ctrl+\\ toggles the tree view, Ctrl+K with an arrow splits a pane, and Ctrl+Shift+M opens the Markdown preview.",
  bindings: {
    "workbench.gotoSymbol": "Ctrl+R",
    "workbench.recent": "",
    "view.explorer": "",
    "view.scm": "",
    "view.extensions": "",
    "view.problems": "",
    "view.output": "",
    "view.toggleSidebar": "Ctrl+\\",
    "view.togglePanel": "",
    "view.focusMode": "",
    "theme.toggle": "",
    "settings.keyboard": "",
    "file.saveAll": "",
    "file.copyPath": "Ctrl+Shift+C",
    "editor.pin": "",
    "editor.keepOpen": "",
    "editor.splitRight": "Ctrl+K ArrowRight",
    "editor.splitDown": "Ctrl+K ArrowDown",
    "editor.moveToNextGroup": "Ctrl+K Ctrl+ArrowRight",
    "editor.replace": "Ctrl+Alt+F",
    "editor.format": "",
    "editor.gotoDefinition": "",
    "editor.references": "",
    "editor.codeAction": "",
    "editor.hover": "",
    "editor.foldAll": "Ctrl+Alt+/",
    "tasks.runBuild": "Ctrl+Alt+B",
    "git.commit": "",
    "preview.markdown": "Ctrl+Shift+M",
    "preview.markdownSide": "",
    "workspace.switch": "",
    "workspace.close": "Ctrl+Shift+W",
  },
};
