import type { Keymap } from "./types.js";
export const emacs: Keymap = {
  stableId: "emacs",
  title: "Emacs",
  description:
    "Emacs defaults: M-x runs a command, C-x C-f finds a file, C-x 2 and C-x 3 split, and C-s searches. Commands with no Emacs equivalent keep their Oxbit binding.",
  bindings: {
    "workbench.showCommands": "Alt+X",
    "workbench.quickOpen": "Ctrl+X Ctrl+F",
    "workbench.gotoSymbol": "",
    "workbench.gotoLine": "Alt+G Alt+G",
    "workbench.recent": "",
    "view.explorer": "Ctrl+X D",
    "view.scm": "Ctrl+X G",
    "view.search": "",
    "view.extensions": "",
    "view.problems": "",
    "view.output": "",
    "view.toggleSidebar": "",
    "view.togglePanel": "",
    "view.focusMode": "",
    "theme.toggle": "",
    "settings.open": "",
    "settings.keyboard": "",
    "file.new": "",
    "file.save": "Ctrl+X Ctrl+S",
    "file.saveAll": "Ctrl+X S",
    "file.rename": "",
    "file.copyPath": "",
    "editor.closeTab": "Ctrl+X K",
    "editor.closeOthers": "Ctrl+X 1",
    "editor.pin": "",
    "editor.keepOpen": "",
    "editor.splitRight": "Ctrl+X 3",
    "editor.splitDown": "Ctrl+X 2",
    "editor.moveToNextGroup": "Ctrl+X O",
    "editor.find": "Ctrl+S",
    "editor.replace": "",
    "editor.format": "Ctrl+Alt+\\",
    "editor.rename": "",
    "editor.gotoDefinition": "Alt+.",
    "editor.references": "",
    "editor.codeAction": "",
    "editor.hover": "Ctrl+H F",
    "editor.suggest": "Alt+/",
    "editor.foldAll": "",
    "editor.unfoldAll": "",
    "editor.toggleWordWrap": "",
    "editor.selectAll": "Ctrl+X H",
    "terminal.new": "",
    "terminal.split": "",
    "terminal.clear": "",
    "tasks.runBuild": "",
    "git.commit": "",
    "preview.markdown": "",
    "preview.markdownSide": "",
    "workspace.open": "",
    "workspace.switch": "",
    "workspace.close": "",
  },
};
