import type { Keymap } from "./types.js";
export const jetbrains: Keymap = {
  stableId: "jetbrains",
  title: "JetBrains",
  description:
    "IntelliJ IDEA, WebStorm, and PyCharm defaults: Ctrl+Shift+A finds an action, Ctrl+B goes to a declaration, Ctrl+K commits, and Alt+digit opens a tool window.",
  bindings: {
    "workbench.showCommands": "Ctrl+Shift+A",
    "workbench.quickOpen": "Ctrl+Shift+N",
    "workbench.gotoSymbol": "Ctrl+F12",
    "view.explorer": "Alt+1",
    "view.scm": "Alt+9",
    "view.problems": "Alt+6",
    "view.output": "Alt+4",
    "view.extensions": "",
    "view.toggleSidebar": "Ctrl+Shift+F12",
    "view.togglePanel": "",
    "view.focusMode": "",
    "theme.toggle": "",
    "settings.open": "Ctrl+Alt+S",
    "settings.keyboard": "",
    "file.new": "Alt+Insert",
    "file.save": "",
    "file.saveAll": "Ctrl+S",
    "file.rename": "Shift+F6",
    "file.copyPath": "Ctrl+Shift+C",
    "editor.closeTab": "Ctrl+F4",
    "editor.pin": "",
    "editor.keepOpen": "",
    "editor.splitRight": "",
    "editor.splitDown": "",
    "editor.moveToNextGroup": "",
    "editor.replace": "Ctrl+R",
    "editor.format": "Ctrl+Alt+L",
    "editor.rename": "Shift+F6",
    "editor.gotoDefinition": "Ctrl+B",
    "editor.references": "Alt+F7",
    "editor.codeAction": "Alt+Enter",
    "editor.hover": "Ctrl+Q",
    "editor.foldAll": "Ctrl+-",
    "editor.unfoldAll": "Ctrl+=",
    "editor.toggleWordWrap": "",
    "terminal.toggle": "Alt+F12",
    "terminal.new": "",
    "terminal.split": "",
    "terminal.clear": "",
    "tasks.runBuild": "Ctrl+F9",
    "tasks.rerun": "Ctrl+F5",
    "tasks.cancel": "Ctrl+F2",
    "git.commit": "Ctrl+K",
    "git.push": "Ctrl+Shift+K",
    "preview.markdown": "",
    "preview.markdownSide": "",
    "workspace.open": "",
    "workspace.switch": "",
    "workspace.close": "",
  },
};
