import type { Keymap } from "./types.js";
export const macos: Keymap = {
  stableId: "macos",
  title: "macOS",
  description:
    "Apple and Xcode conventions: ⌘⇧O opens quickly, ⌘L jumps to a line, ⌘digit switches navigator, ⌘B builds, and ⌘R runs.",
  bindings: {
    "workbench.quickOpen": "Ctrl+Shift+O",
    "workbench.gotoSymbol": "Ctrl+6",
    "workbench.gotoLine": "Ctrl+L",
    "view.explorer": "Ctrl+1",
    "view.scm": "Ctrl+2",
    "view.problems": "Ctrl+5",
    "view.output": "Ctrl+7",
    "view.toggleSidebar": "Ctrl+0",
    "view.togglePanel": "Ctrl+Shift+Y",
    "view.focusMode": "",
    "theme.toggle": "",
    "settings.keyboard": "",
    "file.newFolder": "Ctrl+Alt+N",
    "file.saveAll": "Ctrl+Alt+S",
    "file.reveal": "Ctrl+Shift+J",
    "file.copyPath": "Ctrl+Shift+Alt+C",
    "editor.closeOthers": "Ctrl+Alt+W",
    "editor.pin": "",
    "editor.keepOpen": "",
    "editor.splitRight": "Ctrl+Alt+Enter",
    "editor.splitDown": "",
    "editor.replace": "Ctrl+Alt+F",
    "editor.format": "Ctrl+I",
    "editor.gotoDefinition": "Ctrl+J",
    "editor.references": "Ctrl+Shift+H",
    "editor.codeAction": "Ctrl+Alt+A",
    "editor.hover": "Ctrl+Alt+2",
    "editor.foldAll": "Ctrl+Shift+Alt+ArrowLeft",
    "editor.unfoldAll": "Ctrl+Shift+Alt+ArrowRight",
    "editor.toggleWordWrap": "",
    "terminal.clear": "",
    "tasks.runBuild": "Ctrl+B",
    "tasks.rerun": "Ctrl+R",
    "tasks.cancel": "Ctrl+.",
    "git.commit": "Ctrl+Alt+C",
    "preview.markdownSide": "",
    "workspace.switch": "",
    "workspace.close": "Ctrl+Shift+W",
  },
};
