import type { Keymap } from "./types.js";
export const sublime: Keymap = {
  stableId: "sublime",
  title: "Sublime Text",
  description:
    "Sublime Text defaults: Ctrl+R goes to a symbol, Ctrl+B builds, Ctrl+K Ctrl+B toggles the sidebar, and Alt+W toggles word wrap.",
  bindings: {
    "workbench.gotoSymbol": "Ctrl+R",
    "workbench.recent": "",
    "view.explorer": "",
    "view.scm": "",
    "view.extensions": "",
    "view.problems": "",
    "view.output": "",
    "view.toggleSidebar": "Ctrl+K Ctrl+B",
    "view.focusMode": "Shift+F11",
    "theme.toggle": "",
    "settings.keyboard": "",
    "file.saveAll": "Ctrl+Alt+S",
    "file.copyPath": "",
    "editor.pin": "",
    "editor.keepOpen": "",
    "editor.splitRight": "Ctrl+Alt+2",
    "editor.format": "",
    "editor.codeAction": "",
    "editor.hover": "",
    "editor.foldAll": "Ctrl+K Ctrl+1",
    "editor.toggleWordWrap": "Alt+W",
    "terminal.new": "",
    "terminal.split": "",
    "terminal.clear": "",
    "tasks.run": "Ctrl+Shift+B",
    "tasks.runBuild": "Ctrl+B",
    "git.commit": "",
    "preview.markdown": "",
    "preview.markdownSide": "",
    "workspace.switch": "Ctrl+Alt+P",
    "workspace.close": "",
  },
};
