import type { Keymap } from "./types.js";
export const visualStudio: Keymap = {
  stableId: "visual-studio",
  title: "Visual Studio",
  description:
    "Visual Studio defaults: Ctrl+Q searches, Ctrl+T goes to anything, Ctrl+R Ctrl+R renames, and Ctrl+M Ctrl+O collapses to definitions.",
  bindings: {
    "workbench.showCommands": "Ctrl+Q",
    "workbench.quickOpen": "Ctrl+T",
    "workbench.gotoSymbol": "Alt+\\",
    "workbench.recent": "",
    "view.explorer": "Ctrl+Alt+L",
    "view.scm": "Ctrl+0 Ctrl+G",
    "view.extensions": "",
    "view.problems": "Ctrl+\\ Ctrl+E",
    "view.output": "Ctrl+Alt+O",
    "view.toggleSidebar": "",
    "view.togglePanel": "",
    "view.focusMode": "Shift+Alt+Enter",
    "theme.toggle": "",
    "settings.keyboard": "",
    "file.saveAll": "Ctrl+Shift+S",
    "file.copyPath": "",
    "editor.closeTab": "Ctrl+F4",
    "editor.pin": "",
    "editor.keepOpen": "",
    "editor.splitRight": "",
    "editor.splitDown": "",
    "editor.moveToNextGroup": "",
    "editor.format": "Ctrl+K Ctrl+D",
    "editor.rename": "Ctrl+R Ctrl+R",
    "editor.foldAll": "Ctrl+M Ctrl+O",
    "editor.unfoldAll": "Ctrl+M Ctrl+L",
    "editor.toggleWordWrap": "Ctrl+E Ctrl+W",
    "terminal.new": "",
    "terminal.split": "",
    "terminal.clear": "",
    "git.commit": "",
    "preview.markdown": "",
    "preview.markdownSide": "",
    "workspace.open": "Ctrl+Shift+O",
    "workspace.switch": "",
    "workspace.close": "",
  },
};
